Public Class NameGenerator

#Region " Variables "
    Dim PersonTitle As New List(Of String)

    Dim FirstSyllable As New List(Of String)
    Dim Middle As New List(Of String)
    Dim Ending As New List(Of String)
    Dim Vowels As New List(Of String)
    Dim VowelsPlus As New List(Of String)

    Dim TownStart As New List(Of String)
    Dim TownEnding As New List(Of String)
    Dim TownAdjective As New List(Of String)
    Dim TownPlaces As New List(Of List(Of String))

#End Region

#Region " Functions "

    Public Sub FillLists()
        FillPersonLists()
        FillPlaceLists()
    End Sub

    Public Sub FillPersonLists()
        '--Cleanup
        FirstSyllable.Clear()
        Middle.Clear()
        Ending.Clear()
        Vowels.Clear()
        VowelsPlus.Clear()

        PersonTitle.Add("")
        PersonTitle.Add("Baron ")
        PersonTitle.Add("Baroness ")
        PersonTitle.Add("Dame ")
        PersonTitle.Add("Dr. ")
        PersonTitle.Add("Duchess ")
        PersonTitle.Add("Duke ")
        PersonTitle.Add("Emperor ")
        PersonTitle.Add("Empress ")
        PersonTitle.Add("Lady ")
        PersonTitle.Add("Lord ")
        PersonTitle.Add("Mdm. ")
        PersonTitle.Add("Mr. ")
        PersonTitle.Add("Mrs. ")
        PersonTitle.Add("President ")
        PersonTitle.Add("Prince ")
        PersonTitle.Add("Princess ")
        PersonTitle.Add("Prof. ")
        PersonTitle.Add("Queen ")
        PersonTitle.Add("Sir ")
        PersonTitle.Add("St. ")
        PersonTitle.Add("King ")


        'NameStart.Add("O'")
        'NameStart.Add("Mac")
        'NameStart.Add("Mc")

        '--Vowels
        Vowels.Add("a")
        Vowels.Add("e")
        Vowels.Add("i")
        Vowels.Add("o")
        Vowels.Add("u")
        VowelsPlus.Add("ai")
        VowelsPlus.Add("ea")
        VowelsPlus.Add("au")
        VowelsPlus.Add("oa")
        VowelsPlus.Add("oi")
        VowelsPlus.Add("ou")
        VowelsPlus.Add("oo")
        VowelsPlus.Add("ee")

        '--FirstSyllable
        FirstSyllable.Add("B")
        FirstSyllable.Add("Br")
        FirstSyllable.Add("Bl")
        FirstSyllable.Add("C")
        FirstSyllable.Add("Cr")
        FirstSyllable.Add("Cl")
        FirstSyllable.Add("Ch")
        FirstSyllable.Add("Chr")
        FirstSyllable.Add("Cz")
        FirstSyllable.Add("D")
        FirstSyllable.Add("Dr")
        FirstSyllable.Add("F")
        FirstSyllable.Add("Fr")
        FirstSyllable.Add("Fl")
        FirstSyllable.Add("G")
        FirstSyllable.Add("Gr")
        FirstSyllable.Add("Gl")
        FirstSyllable.Add("Gn")
        FirstSyllable.Add("H")
        FirstSyllable.Add("J")
        FirstSyllable.Add("K")
        FirstSyllable.Add("Kl")
        FirstSyllable.Add("Kn")
        FirstSyllable.Add("Kr")
        FirstSyllable.Add("L")
        FirstSyllable.Add("M")
        FirstSyllable.Add("Mc")
        FirstSyllable.Add("Mac")
        FirstSyllable.Add("N")
        FirstSyllable.Add("P")
        FirstSyllable.Add("Ph")
        FirstSyllable.Add("Pl")
        FirstSyllable.Add("Pr")
        FirstSyllable.Add("Ph")
        FirstSyllable.Add("Qu")
        FirstSyllable.Add("R")
        FirstSyllable.Add("Rh")
        FirstSyllable.Add("S")
        FirstSyllable.Add("St")
        FirstSyllable.Add("Sh")
        FirstSyllable.Add("Sc")
        FirstSyllable.Add("Sk")
        FirstSyllable.Add("Scr")
        FirstSyllable.Add("Shr")
        FirstSyllable.Add("Sn")
        FirstSyllable.Add("Sm")
        FirstSyllable.Add("Sv")
        FirstSyllable.Add("T")
        FirstSyllable.Add("Tr")
        FirstSyllable.Add("Th")
        FirstSyllable.Add("V")
        FirstSyllable.Add("W")
        FirstSyllable.Add("Wr")
        FirstSyllable.Add("Wh")
        FirstSyllable.Add("X")
        FirstSyllable.Add("Y")
        FirstSyllable.Add("Z")

        '--Middle
        Middle.Add("b")
        Middle.Add("bb")
        Middle.Add("c")
        Middle.Add("ck")
        Middle.Add("ch")
        Middle.Add("cr")
        Middle.Add("cc")
        Middle.Add("d")
        Middle.Add("dd")
        Middle.Add("dr")
        Middle.Add("f")
        Middle.Add("ff")
        Middle.Add("fr")
        Middle.Add("g")
        Middle.Add("gr")
        Middle.Add("gg")
        Middle.Add("kk")
        Middle.Add("l")
        Middle.Add("ll")
        Middle.Add("m")
        Middle.Add("mm")
        Middle.Add("n")
        Middle.Add("nn")
        Middle.Add("p")
        Middle.Add("pp")
        Middle.Add("pr")
        Middle.Add("pl")
        Middle.Add("r")
        Middle.Add("rr")
        Middle.Add("s")
        Middle.Add("ss")
        Middle.Add("sh")
        Middle.Add("sc")
        Middle.Add("t")
        Middle.Add("tt")
        Middle.Add("th")
        Middle.Add("tr")
        Middle.Add("v")
        Middle.Add("w")

        '--Endings
        Ending.Add("b")
        Ending.Add("ck")
        Ending.Add("ch")
        Ending.Add("d")
        Ending.Add("f")
        Ending.Add("ff")
        Ending.Add("g")
        Ending.Add("ght")
        Ending.Add("ghton")
        Ending.Add("h")
        Ending.Add("ht")
        Ending.Add("k")
        Ending.Add("l")
        Ending.Add("ll")
        Ending.Add("ler")
        Ending.Add("lm")
        Ending.Add("lt")
        Ending.Add("lp")
        Ending.Add("m")
        Ending.Add("man")
        Ending.Add("m")
        Ending.Add("n")
        Ending.Add("ner")
        Ending.Add("p")
        Ending.Add("que")
        Ending.Add("r")
        Ending.Add("rt")
        Ending.Add("rn")
        Ending.Add("rch")
        Ending.Add("s")
        Ending.Add("ss")
        Ending.Add("st")
        Ending.Add("son")
        Ending.Add("sh")
        'Ending.Add("ski")
        Ending.Add("t")
        Ending.Add("tt")
        Ending.Add("tch")
        Ending.Add("th")
        Ending.Add("ter")
        Ending.Add("ton")
        Ending.Add("vich")
        'Ending.Add("vna")
        Ending.Add("w")
        Ending.Add("x")
        Ending.Add("y")
        Ending.Add("z")
    End Sub

    Public Sub FillPlaceLists()
        '-- Common town name beginnings
        TownStart.Add("Casa de ")
        TownStart.Add("City of ")
        TownStart.Add("Commonwealth of ")
        TownStart.Add("Duchy of ")
        TownStart.Add("Fort ")
        TownStart.Add("House of ")
        TownStart.Add("Land of ")
        TownStart.Add("Monarchy of ")
        'TownStart.Add("Mt. ")
        TownStart.Add("New ")
        TownStart.Add("Ol' ")
        TownStart.Add("Old ")
        'TownStart.Add("Port ")
        TownStart.Add("Republic of ")
        TownStart.Add("Rio de ")
        TownStart.Add("New ")


        '-- Generic town adjectives (usually before a place name like "city")
        TownAdjective.Add("Abandoned ")
        TownAdjective.Add("Amber ")
        TownAdjective.Add("Ancient ")
        TownAdjective.Add("Angry ")
        TownAdjective.Add("Arid ")
        TownAdjective.Add("Armored ")
        TownAdjective.Add("Ascendant ")
        TownAdjective.Add("Ashen ")
        TownAdjective.Add("Auburn ")
        TownAdjective.Add("Azure ")
        TownAdjective.Add("Bald ")
        TownAdjective.Add("Barren ")
        TownAdjective.Add("Beaming ")
        TownAdjective.Add("Beautiful ")
        TownAdjective.Add("Beribboned ")
        TownAdjective.Add("Bitter ")
        TownAdjective.Add("Black ")
        TownAdjective.Add("Blasted ")
        TownAdjective.Add("Blessed ")
        TownAdjective.Add("Blighted ")
        TownAdjective.Add("Bloody ")
        TownAdjective.Add("Blue ")
        TownAdjective.Add("Blustery ")
        TownAdjective.Add("Boistrous ")
        TownAdjective.Add("Bold ")
        TownAdjective.Add("Brave ")
        TownAdjective.Add("Breezy ")
        TownAdjective.Add("Bright ")
        TownAdjective.Add("Broiling ")
        TownAdjective.Add("Broken ")
        TownAdjective.Add("Bronze ")
        TownAdjective.Add("Brooding ")
        TownAdjective.Add("Burnt ")
        TownAdjective.Add("Busy ")
        TownAdjective.Add("Cheerful ")
        TownAdjective.Add("Chilly ")
        TownAdjective.Add("Civilized ")
        TownAdjective.Add("Clear ")
        TownAdjective.Add("Clever ")
        TownAdjective.Add("Cloudy ")
        TownAdjective.Add("Cold ")
        TownAdjective.Add("Copper ")
        TownAdjective.Add("Corrupt ")
        TownAdjective.Add("Coward's ")
        TownAdjective.Add("Craven ")
        TownAdjective.Add("Crimson ")
        TownAdjective.Add("Crippled ")
        TownAdjective.Add("Crooked ")
        TownAdjective.Add("Crowded ")
        TownAdjective.Add("Crystal ")
        TownAdjective.Add("Cursed ")
        TownAdjective.Add("Dangerous ")
        TownAdjective.Add("Dark ")
        TownAdjective.Add("Dead ")
        TownAdjective.Add("Dead Man's ")
        TownAdjective.Add("Deadly ")
        TownAdjective.Add("Decadent ")
        TownAdjective.Add("Deceitful ")
        TownAdjective.Add("Dire ")
        TownAdjective.Add("Dirty ")
        TownAdjective.Add("Disappointing ")
        TownAdjective.Add("Doomed ")
        TownAdjective.Add("Dread ")
        TownAdjective.Add("Drunken ")
        TownAdjective.Add("Dry ")
        TownAdjective.Add("Dusty ")
        TownAdjective.Add("East ")
        TownAdjective.Add("Eccentric ")
        TownAdjective.Add("Elegant ")
        TownAdjective.Add("Emerald ")
        TownAdjective.Add("Esteemed ")
        TownAdjective.Add("Eternal ")
        TownAdjective.Add("Exposed ")
        TownAdjective.Add("Evil ")
        TownAdjective.Add("Fabled ")
        TownAdjective.Add("Fair ")
        TownAdjective.Add("Fallen ")
        TownAdjective.Add("False ")
        TownAdjective.Add("Famous ")
        TownAdjective.Add("Farmer's ")
        TownAdjective.Add("Fatal ")
        TownAdjective.Add("Feral ")
        TownAdjective.Add("Fertile ")
        TownAdjective.Add("Festive ")
        TownAdjective.Add("Fickle ")
        TownAdjective.Add("First ")
        TownAdjective.Add("Foggy ")
        TownAdjective.Add("Fool's ")
        TownAdjective.Add("Forgotten ")
        TownAdjective.Add("Forsaken ")
        TownAdjective.Add("Foul ")
        TownAdjective.Add("Fragrant ")
        TownAdjective.Add("Fresh ")
        TownAdjective.Add("Friendly ")
        TownAdjective.Add("Frigid ")
        TownAdjective.Add("Frosty ")
        TownAdjective.Add("Frozen ")
        TownAdjective.Add("Gated ")
        TownAdjective.Add("Generous ")
        TownAdjective.Add("Giant ")
        TownAdjective.Add("Glistening ")
        TownAdjective.Add("Glorious ")
        TownAdjective.Add("Glowing ")
        TownAdjective.Add("Gnarled ")
        TownAdjective.Add("Golden ")
        TownAdjective.Add("Good ")
        TownAdjective.Add("Gossipy ")
        TownAdjective.Add("Graceful ")
        TownAdjective.Add("Grand ")
        TownAdjective.Add("Grassy ")
        TownAdjective.Add("Gray ")
        TownAdjective.Add("Great ")
        TownAdjective.Add("Greedy ")
        TownAdjective.Add("Green ")
        TownAdjective.Add("Grim ")
        TownAdjective.Add("Happy ")
        TownAdjective.Add("Hard ")
        TownAdjective.Add("Hardy ")
        TownAdjective.Add("Hazy ")
        TownAdjective.Add("Healthy ")
        TownAdjective.Add("Heavonly ")
        TownAdjective.Add("Heavy ")
        TownAdjective.Add("Hellish ")
        TownAdjective.Add("Hero's ")
        TownAdjective.Add("High ")
        TownAdjective.Add("Holy ")
        TownAdjective.Add("Honest ")
        TownAdjective.Add("Hospitable ")
        TownAdjective.Add("Hostile ")
        TownAdjective.Add("Hot ")
        TownAdjective.Add("Humid ")
        TownAdjective.Add("Hungry ")
        TownAdjective.Add("Ignominious ")
        TownAdjective.Add("Imfamous ")
        TownAdjective.Add("Impregnable ")
        TownAdjective.Add("Indomitable ")
        TownAdjective.Add("Inhospitable ")
        TownAdjective.Add("Iron ")
        TownAdjective.Add("Jade ")
        TownAdjective.Add("Jagged ")
        TownAdjective.Add("Joker's ")
        TownAdjective.Add("Kindly ")
        TownAdjective.Add("Knight's ")
        TownAdjective.Add("Lamentable ")
        TownAdjective.Add("Last ")
        TownAdjective.Add("Lasting ")
        TownAdjective.Add("Leafy ")
        TownAdjective.Add("Leaning ")
        TownAdjective.Add("Legendary ")
        TownAdjective.Add("Light ")
        TownAdjective.Add("Lonely ")
        TownAdjective.Add("Long ")
        TownAdjective.Add("Long-Awaited ")
        TownAdjective.Add("Lost ")
        TownAdjective.Add("Lovely ")
        TownAdjective.Add("Lover's ")
        TownAdjective.Add("Low ")
        TownAdjective.Add("Loyal ")
        TownAdjective.Add("Lucky ")
        TownAdjective.Add("Lurking ")
        TownAdjective.Add("Lush ")
        TownAdjective.Add("Majestic ")
        TownAdjective.Add("Martyr's ")
        TownAdjective.Add("Mean ")
        TownAdjective.Add("Merchant's ")
        TownAdjective.Add("Merry ")
        TownAdjective.Add("Mottled ")
        TownAdjective.Add("Muddy ")
        TownAdjective.Add("Musical ")
        TownAdjective.Add("North ")
        TownAdjective.Add("Noxious ")
        TownAdjective.Add("Odd ")
        TownAdjective.Add("Once and Future ")
        TownAdjective.Add("Onyx ")
        TownAdjective.Add("Opal ")
        TownAdjective.Add("Pearl ")
        TownAdjective.Add("Peppy ")
        TownAdjective.Add("Plaid ")
        TownAdjective.Add("Poetic ")
        TownAdjective.Add("Poor ")
        TownAdjective.Add("Primal ")
        TownAdjective.Add("Prismatic ")
        TownAdjective.Add("Prosperous ")
        TownAdjective.Add("Protected ")
        TownAdjective.Add("Proud ")
        TownAdjective.Add("Pure ")
        TownAdjective.Add("Purple ")
        TownAdjective.Add("Quiet ")
        TownAdjective.Add("Rainy ")
        TownAdjective.Add("Receding ")
        TownAdjective.Add("Reclusive ")
        TownAdjective.Add("Red ")
        TownAdjective.Add("Refined ")
        TownAdjective.Add("Reliable ")
        TownAdjective.Add("Rich ")
        TownAdjective.Add("Rising ")
        TownAdjective.Add("Risky ")
        TownAdjective.Add("Riven ")
        TownAdjective.Add("Rocky ")
        TownAdjective.Add("Royal ")
        TownAdjective.Add("Ruby ")
        TownAdjective.Add("Ruined ")
        TownAdjective.Add("Sacred ")
        TownAdjective.Add("Safe ")
        TownAdjective.Add("Salty ")
        TownAdjective.Add("Sandy ")
        TownAdjective.Add("Sapphire ")
        TownAdjective.Add("Scarred ")
        TownAdjective.Add("Scrappy ")
        TownAdjective.Add("Secret ")
        TownAdjective.Add("Shadowy ")
        TownAdjective.Add("Shady ")
        TownAdjective.Add("Shameful ")
        TownAdjective.Add("Sheltered ")
        TownAdjective.Add("Shining ")
        TownAdjective.Add("Short ")
        TownAdjective.Add("Shrewd ")
        TownAdjective.Add("Silver ")
        TownAdjective.Add("Slave's ")
        TownAdjective.Add("Smoky ")
        TownAdjective.Add("Soft ")
        TownAdjective.Add("Soldier's ")
        TownAdjective.Add("Solitary ")
        TownAdjective.Add("Sour ")
        TownAdjective.Add("South ")
        TownAdjective.Add("Split ")
        TownAdjective.Add("Speckled ")
        TownAdjective.Add("Spicy ")
        TownAdjective.Add("Spotted ")
        TownAdjective.Add("Squalid ")
        TownAdjective.Add("Squatter's ")
        TownAdjective.Add("Steel ")
        TownAdjective.Add("Stony ")
        TownAdjective.Add("Stormy ")
        TownAdjective.Add("Straight ")
        TownAdjective.Add("Striped ")
        TownAdjective.Add("Strong ")
        TownAdjective.Add("Sturdy ")
        TownAdjective.Add("Sulphurous ")
        TownAdjective.Add("Sunken ")
        TownAdjective.Add("Sunny ")
        TownAdjective.Add("Sweet ")
        TownAdjective.Add("Sylvan ")
        TownAdjective.Add("Tall ")
        TownAdjective.Add("Thief's ")
        TownAdjective.Add("Thirsty ")
        TownAdjective.Add("Tilted ")
        TownAdjective.Add("Tiny ")
        TownAdjective.Add("Towering ")
        TownAdjective.Add("Traitor's ")
        TownAdjective.Add("Traveler's ")
        TownAdjective.Add("Treacherous ")
        TownAdjective.Add("True ")
        TownAdjective.Add("Trusty ")
        TownAdjective.Add("Twin ")
        TownAdjective.Add("Twinkling ")
        TownAdjective.Add("Twisted ")
        TownAdjective.Add("Ugly ")
        TownAdjective.Add("Ultimate ")
        TownAdjective.Add("Unbroken ")
        TownAdjective.Add("Undaunted ")
        TownAdjective.Add("Unholy ")
        TownAdjective.Add("Unlucky ")
        TownAdjective.Add("Unworthy ")
        TownAdjective.Add("Verdant ")
        TownAdjective.Add("Vivid ")
        TownAdjective.Add("Vulgar ")
        TownAdjective.Add("Walled ")
        TownAdjective.Add("Waning ")
        TownAdjective.Add("Warm ")
        TownAdjective.Add("Weak ")
        TownAdjective.Add("Wealthy ")
        TownAdjective.Add("Welcoming ")
        TownAdjective.Add("West ")
        TownAdjective.Add("Wet ")
        TownAdjective.Add("Whispering ")
        TownAdjective.Add("White ")
        TownAdjective.Add("Wicked ")
        TownAdjective.Add("Wild ")
        TownAdjective.Add("Windy ")
        TownAdjective.Add("Wise ")
        TownAdjective.Add("Wooded ")
        TownAdjective.Add("Worthy ")
        TownAdjective.Add("Yellow ")
        TownAdjective.Add("Zesty ")


        '-- Common town name endings
        TownEnding.Add("burg")
        TownEnding.Add("grad")
        TownEnding.Add("ham")
        TownEnding.Add("istan")
        TownEnding.Add("land")
        TownEnding.Add("let")
        TownEnding.Add("polis")
        TownEnding.Add("shire")
        TownEnding.Add("town")
        TownEnding.Add("ville")



        '-- PLAINS - Anything open, grassy, or farmable. Plus generic placenames as this is the most common terrain type.
        Dim TownPlacePlain As New List(Of String)
        For i As Integer = 0 To 8
            TownPlacePlain.Add("City")
        Next
        For i As Integer = 0 To 6
            TownPlacePlain.Add("Town")
        Next
        For i As Integer = 0 To 4
            TownPlacePlain.Add("Village")
        Next
        TownPlacePlain.Add("Acres")
        TownPlacePlain.Add("Borough")
        TownPlacePlain.Add("Castle")
        TownPlacePlain.Add("Croft")
        TownPlacePlain.Add("Crops")
        TownPlacePlain.Add("Den")
        TownPlacePlain.Add("Distrct")
        TownPlacePlain.Add("Domain")
        TownPlacePlain.Add("Estate")
        TownPlacePlain.Add("Farm")
        TownPlacePlain.Add("Feld")
        TownPlacePlain.Add("Field")
        TownPlacePlain.Add("Garden")
        TownPlacePlain.Add("Grassland")
        TownPlacePlain.Add("Hamlet")
        TownPlacePlain.Add("Heath")
        TownPlacePlain.Add("Homestead")
        TownPlacePlain.Add("Keep")
        TownPlacePlain.Add("Manor")
        TownPlacePlain.Add("Meadow")
        TownPlacePlain.Add("Moor")
        TownPlacePlain.Add("Oblast")
        TownPlacePlain.Add("Park")
        TownPlacePlain.Add("Pasture")
        TownPlacePlain.Add("Plains")
        TownPlacePlain.Add("Prairie")
        TownPlacePlain.Add("Province")
        TownPlacePlain.Add("Ranch")
        TownPlacePlain.Add("Realm")
        TownPlacePlain.Add("Region")
        TownPlacePlain.Add("Savannah")
        TownPlacePlain.Add("Shrubland")
        TownPlacePlain.Add("Spire")
        TownPlacePlain.Add("Steppe")
        TownPlacePlain.Add("Territory")
        TownPlacePlain.Add("Tower")
        TownPlacePlain.Add("Tract")
        TownPlacePlain.Add("Valley")
        TownPlacePlain.Add("Veldt")
        TownPlacePlain.Add("Zone")
        TownPlaces.Add(TownPlacePlain)

        '-- DIRT - Lowloands, hills, and travel words like 'road'
        Dim TownPlaceDirt As New List(Of String)
        TownPlaceDirt.Add("Butte")
        TownPlaceDirt.Add("Byway")
        TownPlaceDirt.Add("Crossing")
        TownPlaceDirt.Add("Crossroads")
        TownPlaceDirt.Add("Downs")
        TownPlaceDirt.Add("Flats")
        TownPlaceDirt.Add("Hill")
        TownPlaceDirt.Add("Hills")
        TownPlaceDirt.Add("Knoll")
        TownPlaceDirt.Add("Lane")
        TownPlaceDirt.Add("Mound")
        TownPlaceDirt.Add("Passage")
        TownPlaceDirt.Add("Road")
        TownPlaceDirt.Add("Route")
        TownPlaceDirt.Add("Tundra")
        TownPlaceDirt.Add("Way")
        TownPlaces.Add(TownPlaceDirt)

        '-- FOREST - Anything involving trees
        Dim TownPlaceForest As New List(Of String)
        TownPlaceForest.Add("Arboretum")
        TownPlaceForest.Add("Birch")
        TownPlaceForest.Add("Canopy")
        TownPlaceForest.Add("Clearing")
        TownPlaceForest.Add("Copse")
        TownPlaceForest.Add("Elms")
        TownPlaceForest.Add("Evergreens")
        TownPlaceForest.Add("Firs")
        TownPlaceForest.Add("Forest")
        TownPlaceForest.Add("Glade")
        TownPlaceForest.Add("Grotto")
        TownPlaceForest.Add("Hollow")
        TownPlaceForest.Add("Jungle")
        TownPlaceForest.Add("Maples")
        TownPlaceForest.Add("Mushrooms")
        TownPlaceForest.Add("Oaks")
        TownPlaceForest.Add("Orchard")
        TownPlaceForest.Add("Overgrowth")
        TownPlaceForest.Add("Pines")
        TownPlaceForest.Add("Poplars")
        TownPlaceForest.Add("Rainforest")
        TownPlaceForest.Add("Stumps")
        TownPlaceForest.Add("Thicket")
        TownPlaceForest.Add("Timberland")
        TownPlaceForest.Add("Weald")
        TownPlaceForest.Add("Wilderness")
        TownPlaceForest.Add("Wood")
        TownPlaceForest.Add("Woods")
        TownPlaces.Add(TownPlaceForest)

        '-- MOUNTAIN - Anything elevated or rocky
        Dim TownPlaceMountain As New List(Of String)
        TownPlaceMountain.Add("Bluff")
        TownPlaceMountain.Add("Cavern")
        TownPlaceMountain.Add("Caves")
        TownPlaceMountain.Add("Chasm")
        TownPlaceMountain.Add("Cliffs")
        TownPlaceMountain.Add("Crest")
        TownPlaceMountain.Add("Deep")
        TownPlaceMountain.Add("Falls")
        TownPlaceMountain.Add("Leap")
        TownPlaceMountain.Add("Mesa")
        TownPlaceMountain.Add("Mine")
        TownPlaceMountain.Add("Mount")
        TownPlaceMountain.Add("Mountain")
        TownPlaceMountain.Add("Outlook")
        TownPlaceMountain.Add("Overlook")
        TownPlaceMountain.Add("Pass")
        TownPlaceMountain.Add("Peaks")
        TownPlaceMountain.Add("Ravine")
        TownPlaceMountain.Add("Ridge")
        TownPlaceMountain.Add("Snowcaps")
        TownPlaceMountain.Add("Spring")
        TownPlaceMountain.Add("View")
        TownPlaceMountain.Add("Vista")


        TownPlaces.Add(TownPlaceMountain)

        '-- COASTAL - Words involving moving or stationary water
        Dim TownPlaceLake As New List(Of String)
        TownPlaceLake.Add("Bay")
        TownPlaceLake.Add("Beach")
        TownPlaceLake.Add("Bridge")
        TownPlaceLake.Add("Brook")
        TownPlaceLake.Add("by the Sea")
        TownPlaceLake.Add("Cape")
        TownPlaceLake.Add("Coast")
        TownPlaceLake.Add("Creek")
        TownPlaceLake.Add("Dam")
        TownPlaceLake.Add("Delta")
        TownPlaceLake.Add("Delta")
        TownPlaceLake.Add("Docks")
        TownPlaceLake.Add("Ferry")
        TownPlaceLake.Add("Fjord")
        TownPlaceLake.Add("Harbor")
        TownPlaceLake.Add("Inlet")
        TownPlaceLake.Add("Lagoon")
        TownPlaceLake.Add("Lake")
        TownPlaceLake.Add("Landing")
        TownPlaceLake.Add("Pond")
        TownPlaceLake.Add("Pools")
        TownPlaceLake.Add("Port")
        TownPlaceLake.Add("Reservoir")
        TownPlaceLake.Add("River")
        TownPlaceLake.Add("Shoals")
        TownPlaceLake.Add("Shore")
        TownPlaceLake.Add("Strait")
        TownPlaceLake.Add("Stream")
        TownPlaceLake.Add("Tides")
        TownPlaces.Add(TownPlaceLake)

        '-- SWAMP - Anything marshy or unpleasant
        Dim TownPlaceSwamp As New List(Of String)
        TownPlaceSwamp.Add("Basin")
        TownPlaceSwamp.Add("Bayou")
        TownPlaceSwamp.Add("Bog")
        TownPlaceSwamp.Add("Cesspool")
        TownPlaceSwamp.Add("Dump")
        TownPlaceSwamp.Add("End")
        TownPlaceSwamp.Add("Everglade")
        TownPlaceSwamp.Add("Fen")
        TownPlaceSwamp.Add("Folly")
        TownPlaceSwamp.Add("Marsh")
        TownPlaceSwamp.Add("Morass")
        TownPlaceSwamp.Add("Ooze")
        TownPlaceSwamp.Add("Peat")
        TownPlaceSwamp.Add("Pit")
        TownPlaceSwamp.Add("Quagmire")
        TownPlaceSwamp.Add("Slime")
        TownPlaceSwamp.Add("Swamp")
        TownPlaceSwamp.Add("Wetland")
        TownPlaces.Add(TownPlaceSwamp)

        '-- Township - Anything populated or communal
        Dim TownPlaceTownship As New List(Of String)
        TownPlaceTownship.Add("Abbey")
        TownPlaceTownship.Add("Bazaar")
        TownPlaceTownship.Add("Cathedral")
        TownPlaceTownship.Add("Church")
        TownPlaceTownship.Add("Cloister")
        TownPlaceTownship.Add("Commune")
        TownPlaceTownship.Add("Grounds")
        TownPlaceTownship.Add("Hall")
        TownPlaceTownship.Add("Inn")
        TownPlaceTownship.Add("Market")
        TownPlaceTownship.Add("Monastery")
        TownPlaceTownship.Add("Plantation")
        TownPlaceTownship.Add("Square")
        TownPlaceTownship.Add("Stable")
        TownPlaceTownship.Add("Station")
        TownPlaceTownship.Add("Subdivision")
        TownPlaceTownship.Add("Township")
        TownPlaceTownship.Add("Trading Post")
        TownPlaces.Add(TownPlaceTownship)

        '-- Desert - Anything sandy, dry, or destitute
        Dim TownPlaceDesert As New List(Of String)
        TownPlaceDesert.Add("Badland")
        TownPlaceDesert.Add("Cemetery")
        TownPlaceDesert.Add("Crater")
        TownPlaceDesert.Add("Desert")
        TownPlaceDesert.Add("Dunes")
        TownPlaceDesert.Add("Oasis")
        TownPlaceDesert.Add("Palms")
        TownPlaceDesert.Add("Ruins")
        TownPlaceDesert.Add("Sands")
        TownPlaceDesert.Add("Shrine")
        TownPlaceDesert.Add("Temple")
        TownPlaceDesert.Add("Wasteland")
        TownPlaceDesert.Add("Wastes")
        TownPlaces.Add(TownPlaceDesert)


    End Sub

    Public Function GenerateCityName(ByRef theLocation As CitySquare) As String
        Dim nameStr As String = ""

        '-- Front text
        If GetRandom(0, 9) = 0 Then
            nameStr += TownStart(GetRandom(0, TownStart.Count - 1))
        End If

        Dim requirePlaceName As Boolean = False
        If GetRandom(0, 2) = 0 Then
            '-- Adjective
            nameStr += TownAdjective(GetRandom(0, TownAdjective.Count - 1))
            requirePlaceName = True

            If GetRandom(0, 9) = 0 Then
                '-- Rare double adjective
                nameStr += TownAdjective(GetRandom(0, TownAdjective.Count - 1))
            End If
        Else
            '-- Title
            Dim cityEnding As Integer = GetRandom(0, 6)
            If cityEnding = 0 Then
                nameStr += PersonTitle(GetRandom(0, PersonTitle.Count - 1))
            End If

            '-- Random name
            nameStr += GeneratePersonName()

            If cityEnding = 0 Then
                '-- Posessive
                nameStr += "'s "
                requirePlaceName = True
            ElseIf cityEnding = 1 Or cityEnding = 2 Then
                '-- Classic endings
                nameStr += TownEnding(GetRandom(0, TownEnding.Count - 1))
            End If
        End If

        If GetRandom(0, 1) = 0 Or requirePlaceName Then
            If Not requirePlaceName Then
                nameStr += " "
            End If

            '-- Get place name based on terrain type
            Dim terrainIndex As Integer = theLocation.Terrain
            If theLocation.Coastal Then
                If GetRandom(0, 1) = 0 Then
                    terrainIndex = TerrainLake
                End If
            End If

            Dim placeList As List(Of String) = TownPlaces(terrainIndex)
            nameStr += placeList(GetRandom(0, placeList.Count - 1))

        End If

        Return nameStr

    End Function

    Public Function GeneratePersonName() As String
        Dim nameStr As String = ""

        '--First Syllable
        If GetRandom(0, 100) <= 15 Then
            '-- Start with a vowel
            nameStr += Vowels(GetRandom(0, Vowels.Count - 1))
        Else
            nameStr += FirstSyllable(GetRandom(0, FirstSyllable.Count - 1))

            '--First Vowel
            If GetRandom(0, 2) <= 1 Then
                nameStr += Vowels(GetRandom(0, Vowels.Count - 1))
            Else
                nameStr += VowelsPlus(GetRandom(0, VowelsPlus.Count - 1))
            End If

            '-- Super short name
            If GetRandom(0, 15) = 0 Then
                Return nameStr
            End If
        End If

        '-- Capitalize first letter
        nameStr = nameStr.Substring(0, 1).ToUpper() + nameStr.Substring(1)

        '--Second Syllable
        If GetRandom(0, 1) = 0 Then
            nameStr += Middle(GetRandom(0, Middle.Count - 1))
        Else
            'Last Syllable
            nameStr += Ending(GetRandom(0, Ending.Count - 1))
            '--Final Vowel
            If GetRandom(0, 3) = 0 Then
                nameStr += Vowels(GetRandom(0, Vowels.Count - 1))
            End If
            Return nameStr
        End If

        '--Second Vowel
        If GetRandom(0, 2) <= 1 Then
            nameStr += Vowels(GetRandom(0, Vowels.Count - 1))
        Else
            nameStr += VowelsPlus(GetRandom(0, VowelsPlus.Count - 1))
        End If

        '--Third Syllable
        nameStr += Ending(GetRandom(0, Ending.Count - 1))
        '--Final Vowel
        If GetRandom(0, 3) = 0 Then
            nameStr += Vowels(GetRandom(0, Vowels.Count - 1))
        End If

        Return nameStr
    End Function

#End Region
End Class
